# AWS playbook
---

- hosts: aws
  gather_facts: False

  vars:
    key_name: Ib_Bo_aws
    region: eu-west-1
    image: ami-05ec38f16b5a19c94
    id: "Eng67.Ib.App.Ansible"
    sec_group: "sg-09b595c4da0ffbab3"
    subnet_id: "subnet-0b83d000d36ae0c5c"

  tasks:

    - name: Facts
      block:

      - name: Get instances facts
        ec2_instance_facts:
          aws_access_key: "{{ec2_access_key}}"
          aws_secret_key: "{{ec2_secret_key}}"
          region: "{{ region }}"
        register: result

      tags: always


    - name: Provisioning EC2 instances
      block:

      - name: Upload public key to AWS
        ec2_key:
          name: "{{ key_name }}"
          key_material: "{{ lookup('file', '~/.ssh/{{ key_name }}.pub') }}"
          region: "{{ region }}"
          aws_access_key: "{{ec2_access_key}}"
          aws_secret_key: "{{ec2_secret_key}}"

      - name: Provision instance(s)
        ec2:
          aws_access_key: "{{ec2_access_key}}"
          aws_secret_key: "{{ec2_secret_key}}"
          assign_public_ip: true
          key_name: "{{ key_name }}"
          id: "{{ id }}"
          group_id: "{{ sec_group }}"
          vpc_subnet_id: "{{ subnet_id }}"
          image: "{{ image }}"
          instance_type: t2.micro
          region: "{{ region }}"
          wait: true
          count: 1
          # exact_count: 2
          count_tag:
            instance_tags:
              Name: "{{ id }}"

      tags: ['never', 'create_ec2']



      - name: Start instance
      - ec2_instance:
        state: restarted
        instance_ids:
          - i-04e7e2b64d88183f4

      tags: ['never', 'start_ec2']



